### ISSUE TITLE
Add option for skipping url and menu screen when loading widget or application

### ISSUE THREAD

**Issue by erlendsellie** [house-of-abbey/GarminHomeAssistant#102]
Really like this app!
My main cavet with this app is the API and Menu check that is done when starting the app. Would it be possible to add an option to disable it, and just load the cached menu?
That would save a click each time i want to toggle a light or similar.

Thanks for the work on this project.

**Comment by philipabbey** [comment]
Are you using the widget or the application? See https://github.com/house-of-abbey/GarminHomeAssistant?tab=readme-ov-file#widget-or-application

If you are using the application, then you can start it directly (like I do) from the application menu. I have mine pinned as the first favourite (as explained in the link above). You can also start the application via the glance, but equally you can remove the glance if it is clutter.

If you are using the widget, then see the settings described at https://github.com/house-of-abbey/GarminHomeAssistant?tab=readme-ov-file#settings

> Another toggle setting for the Widget version only allows the user to select a non-standard user interface behaviour. As soon as the menu is retrieved the widget view is replaced by the menu without waiting for a user selection. This has been included as requested by a user, but defaults to off which retains the expected user interactions.

Please can I ask that you review the documentation before raising issues?

**Comment by erlendsellie** [comment]
Thanks for the really swift reply!
Turns out installing it as an application solved the problem. I was a bit perplexed as i had both installed, but i mixed the words glance and widget. 

I was looking for this in the documentation before submitting the issue/question, but didn't catch the part you refe to about this menu. Sorry for the inconvenience, but thanks again for the quick and good answer.
