### ISSUE TITLE
Feature Request - allow installation on Garmin Edge Computers

### ISSUE THREAD

**Issue by velaar** [house-of-abbey/GarminHomeAssistant#106]
As per the topic title, I believe battery tracking is via homeassistant for Garmin Edge computers can be extremely helpful. As the app is menu-based I anticipate little to no compatibility issues.

**Comment by JosephAbbey** [comment]
It seems that two of the edge devices do not support a new enough API level (we use 3.1+), this means that they do not have necessary features for the app. However, we do have support for many of them.

Here are the currently supported Edge devices:
- [x] Edge 520 Plus
- [x] Edge 530
- [ ] Edge 540 / 540 Solar
- [x] Edge 820 / Explore
- [x] Edge 830
- [ ] Edge 840 / 840 Solar
- [x] Edge 1030
- [x] Edge 1030 / Bontrager
- [x] Edge 1030 Plus
- [x] Edge 1040 / 1040 Solar
- [x] Edge Explore
- [x] Edge Explore 2

**Comment by velaar** [comment]
@JosephAbbey  I'm apologies for responding to a closed request. But can you please double check the 540/840 compatibility? 
As per this page: https://developer.garmin.com/connect-iq/compatible-devices/ both devices have an API level of 4.2.0 - same as the 1040 that is supported. 

Thank you!

**Comment by philipabbey** [comment]
Please see [known issues](https://github.com/house-of-abbey/GarminHomeAssistant?tab=readme-ov-file#known-issues) point 6. We have tried and failed. Sorry.
