### ISSUE TITLE
Newline character

### ISSUE THREAD

**Issue by geotibi** [house-of-abbey/GarminHomeAssistant#111]
Hello,

Is it possible to use the new line in a sensor display? if yes, how I should proceed?
I've tried with \\n, \n, \r\n but doesn't work. I want to put temperature on 1st line and humidity on 2nd line

          "type": "template",
          "content": "🌡️ {{ states('sensor.0xa4c138a6f9c619b5_temperature') }}°C, 💧 {{ states('sensor.0xa4c138a6f9c619b5_humidity') }}%"

**Comment by JosephAbbey** [comment]
Hi @geotibi,

The built in menu UI that we use only supports a single line for text. So, unfortunately, we cannot easily provide a solution to this problem.

The status must be one line.

*.. Joseph*
