### ISSUE TITLE
Question: Internal http access not working

### ISSUE THREAD

**Issue by janlang** [house-of-abbey/GarminHomeAssistant#112]
Hi,

very nice implementation! I have a question how can I use an internal connection without https. I dont want to make the homeassistant instance accessible from the internet. The clock only needs the internal connection via http. At the moment that does not seem to work. This is true for the api as well as the Menu.json file.
Cheers Jan

**Comment by JosephAbbey** [comment]
Hi @janlang,

Due to limitations of the ConnectIQ SDK, we cannot offer support for HTTP in the app.

[Documentation](https://github.com/house-of-abbey/GarminHomeAssistant#garminhomeassistant)
> It is important to note that your Home Assistant instance will need to be accessible via HTTPS with public SSL or all requests from the Garmin will not work. This cannot be a self-signed certificate, it must be a public certificate. You can get one for free from [Let's Encrypt](https://letsencrypt.org/) or you can pay for [Home Assistant cloud](https://www.nabucasa.com/). (You can install a local [Nginx proxy server](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_nginxproxymanager) to manage Let's Encrypt certificates.)

*.. Joseph*

**Comment by philipabbey** [comment]
You can do (almost) the same as we have done in our [Trouble Shooting guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md#do-it-yourself-setup). Create a proxy that forwards HTTPS to Home Assistant HTTP. If you use Nginx as the web server you can then use Let's Encrypt for free certificates. Next you need to make sure that the hostname in the certificate can be resolved locally. E.g. adding ther hostname to your local DNS.

I am aware that another user has done something similar and got it working. See the end of this [conversation trail](https://community.home-assistant.io/t/home-assistant-app-for-garmin/637348/164).

**Comment by janlang** [comment]
Ah, I was not aware of the ConnectIQ SDK limitation. The trouble shooting thing I have seen. I hoped that there is an easier solution. Thanks for the answers!
