### ISSUE TITLE
Splitting widget and app code

### ISSUE THREAD

**Issue by Someone0nEarth** [house-of-abbey/GarminHomeAssistant#113]
### Goals

1. Having a code base for the app version without "legacy" widget code for achieving space to add new features.
2. Set the widget version to maintenance only mode (feature freeze, only bug fixing etc.)

### Proposal

New repository under "house-of-abbey" for the widget version. For example: "GarminHomeAssistantWidget".

Cloning the current code base into it. Removing all the "legacy" widget related code from the app repo and removing all the glance code in the widget version. 

Set the widget repo to "maintenance only mode" by making this clear in the readme.

**Comment by Someone0nEarth** [comment]
@philipabbey What do you think? I could do the widget repo cleanup, because I can test it on my Venu.

**Comment by philipabbey** [comment]
I was wondering if we had one Github repo with two source trees, which might confuse the tools, or two separate Github repos altogether?

**Comment by Someone0nEarth** [comment]
I think have two repos is the most clean and straight forwarded  solution:

The widget code will be legacy code, which will only be changed for a bug fixing. It is unlikely, that it will be touch at all. And if it will be touch, even the commit history will be more cleaner because it will be dedicated. 
It will make the app repo more clean, too. And it will be easier for all the tooling, to have separate repos.

I am not seeing any significant downsides for having two repos for this scenario. Or am I missing something here?

**Comment by JosephAbbey** [comment]
New repo: https://github.com/house-of-abbey/GarminHomeAssistantWidget

Now we need to remove the irrelevant parts.

*.. Joseph*

**Comment by Someone0nEarth** [comment]
> New repo: https://github.com/house-of-abbey/GarminHomeAssistantWidget
> 
> Now we need to remove the irrelevant parts.

I will do it for the Widget repo ✌️

**Comment by philipabbey** [comment]
> > New repo: https://github.com/house-of-abbey/GarminHomeAssistantWidget
> > Now we need to remove the irrelevant parts.
> 
> I will do it for the Widget repo ✌️

Thank you. Happy to re-deploy a new version under the existing ID when you have completed the separation.

**Comment by philipabbey** [comment]
This issue will be continued for the rationalising of the application code.
