### ISSUE TITLE
Allow turning off vibration

### ISSUE THREAD

**Issue by WebSpider** [house-of-abbey/GarminHomeAssistant#118]
**Is your feature request related to a problem? Please describe.**
When making this app available to my partner, she didn't like the vibration caused by executing actions.

**Describe the solution you'd like**
Add an ability to disable vibrations, either in the app's IQ store configuration or in the dashboard definition

**Describe alternatives you've considered**
Turn off the vibration globally in the watch, this is not desireable to my partner

**Additional context**
~~

**Comment by philipabbey** [comment]
Include: Fix a dereferencing null bug in HomeAssistantService.mc

Amend this:

```
var entity_id = data.get("entity_id");
if (entity_id == null) {
    entity_id = "";
}
```

To this:

```
var entity_id = "";
if (data != null) {
    entity_id = data.get("entity_id");
    if (entity_id == null) {
        entity_id = "";
    }
}
```

**Comment by WebSpider** [comment]
Wow, thanks for the quick followup! :partying_face:
