### ISSUE TITLE
Make the font size configurable

### ISSUE THREAD

**Issue by jose1711** [house-of-abbey/GarminHomeAssistant#127]
Would it be possible to customize the menu font size? Specifically I would welcome to be able to see more than just 3 rows of output on my EPIX watch.

**Comment by philipabbey** [comment]
We are using ConnectIQ menu items. You get what they give you. They tend to give you a common look and feel for your device. Customising these would be painful given the variety of styles and watch sizes hence we stick to the stock menu item.

Sorry, this is not in our gift.
