### ISSUE TITLE
Examples could show some usage of unicode characters

### ISSUE THREAD

**Issue by jose1711** [house-of-abbey/GarminHomeAssistant#128]
This will probably not be the case with all Garmin models but it may still be worth mentioning that newer models support a wide range of unicode characters that may be used in menu items/template values, e. g.:
```
💡 on/off
  🛋  Living room
  🛏  Bedroom
  🍲 Kitchen
🎨 color
  🔴 red
  🔵 blue
  🟢 green
📺 TV
💻 PC
🔈 Speaker
```
All render very nicely on my EPIX 2.

**Comment by philipabbey** [comment]
Yes, I do use a few of these charaters in my own configuration. By all means submit a pull request for your preferred examples.

**Comment by philipabbey** [comment]
https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/examples/Templates.md#examples Just a quick example.
