### ISSUE TITLE
[Widget] Auto start doesn't work when menu is cached 

### ISSUE THREAD

**Issue by tomasjiricek** [house-of-abbey/GarminHomeAssistant#134]
**Describe the bug**
When I enable the automatic start after launching (no waiting for tap), it doesn't work when the menu is cached (enabled caching of menu in settings).

**IMPORTANT!**
I have:

- [x] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. Go to Connect IQ widget settings
2. Enable caching of menu and automatic start without waiting for tap
3. On the watch, if not cached:
- open the widget
- let the app load entities/items
- close the widget, exit it completely
4. Open the widget
5. See the widget showing "API" and "Menu" (cached)
6. See error (not proceeding to menu)

**Expected behavior**
Starting the widget with enabled "automatically start without waiting for tap", it should proceed to menu, instead of waiting for tap.

**Screenshots**

**Garmin Device (please complete the following information):**

- Model: Fenix 6X Sapphire

**Smartphone (please complete the following information):**

- Device: Samsung S23
- OS: Android 14

**Additional context**

**Comment by philipabbey** [comment]
I'll mark this as a bug when I have decided it is so!

In the mean time, as we know that auto start does work on other devices, I need to check that you have installed the correct application as there are two. The application at https://github.com/house-of-abbey/GarminHomeAssistant does not support Widgets or autostart, the Widget at https://github.com/house-of-abbey/GarminHomeAssistantWidget does. I need to be sure you have installed the latter before this is a bug.

Thank you for reporting this, I will try and find some time later in the week to follow your instructions to reproduce using the simulator. Presently I am between desktop PCs and without the means to run up the code.

**Comment by Someone0nEarth** [comment]
> There is definitely a bug here.

In the app or in the widget version? @philipabbey

**Comment by philipabbey** [comment]
> In the app or in the widget version?

Only the widget version as the app does not have a root view.

**Comment by Someone0nEarth** [comment]
> > In the app or in the widget version?
> 
> Only the widget version as the app does not have a root view. Shouldn't be too hard to fix.

True. Will have a look on this. Also creating an issue for the widget repo.

**Comment by philipabbey** [comment]
This issue has been transferred to the correct repo and is now fixed.
