### ISSUE TITLE
[String Change Request] Czech translation inappropriate

### ISSUE THREAD

**Issue by tomasjiricek** [house-of-abbey/GarminHomeAssistant#135]
Strings in Czech translation (resources-ces) are inappropriate.
Strings affected (IDs):
- `Confirm` ("Tak určitě?" - hard to translate, simply not how we would ask)
- `GlanceMenu` ("Jídelní lístek" - this means lunch menu)
- `Available` ("Dostupný" - grammatically incorrect when meant for API and Menu)

Appropriate translation:
- `Confirm`: "Určitě?"
- `GlanceMenu`: "Menu"
- `Available`: "Dostupné"

**Comment by philipabbey** [comment]
Are you able to submit your preferred corrections by following the instructions at https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/README.md#submitting-corrections-for-translations?

**Comment by philipabbey** [comment]
Corrections are now in the latest version for download.
