### ISSUE TITLE
Error code 401 being returned for non-administrator user

### ISSUE THREAD

**Issue by johnwelford** [house-of-abbey/GarminHomeAssistant#140]
Error code 401 being returned for non-administrator user.

I have:

- [x] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**
1. Made a functional setup for an administrator user
2. Copy the same setup to a user account that is not an administrator
3. Set up a new API key for the user and copy across
4. Opening on Garmin gives "HTTP requset returned error code = 401" and no functionality
5. Setting the user account to  administrator removes the error and gives normal functionality

**Expected behavior**
Did not expect that administrator level user account was necessary

**Garmin Device (please complete the following information):**

- Model: Forerunner 245 Music

**Smartphone (please complete the following information):**

- Device: iPhoneSE
- OS: iOS17.4.1

**Additional context**
Similar to issue 39, but without battery reporting being turned on?

**Comment by philipabbey** [comment]
We have non-Administrators using the application just fine. Your steps for recreating the bug may well not work for another JSON file. We know from previous experience that issues have been localised to a specific menu item.
- Can you isolate which menu item(s) is/are causing the issue as that provides a clue? Without this information this issue will have to be parked as it is too non-specific.
- Did the web-based configuration editor also fail for the non-Administrator user? The reason for asking is I'm trying to discriminate between the JSON menu file causing the 401 error (that should be independent of any API access and hence independent of any API key) and the API call doing so.
- Do you have any insights into how permissions may affect HA entities?

This may well be a show stopper. We did not expect Administrator priviledges to be getting in the way either. There is absolutely no promise this can be fixed.

**Comment by Skyslycer** [comment]
I have a similar issue. All my toggles/switches work fine, but once I wanted to add a template, every time I open the app on the watch, a 401 error appears.
```
    {
      "entity": "sensor.a1_03919c430600775_verbleibende_zeit",
      "name": "Time Left",
      "type": "template",
      "content": "{{ states('sensor.a1_03919c430600775_verbleibende_zeit') }}"
    },
```
![image](https://github.com/house-of-abbey/GarminHomeAssistant/assets/73074974/5e30d470-050a-4518-9542-dd774fd44963)
The web viewer underlines the entity name as it does with any other entity (which works) in the menu file. All my other entities (toggles) work from the web viewer too, but pressing "Render Template" just causes the screen to gray out and having to press "Test API" in the Troubleshooting window again to be able to edit the template again. I don't know what's going on since I can view the entity just fine on the actual website.

**Comment by JosephAbbey** [comment]
I think that the issue is that we are using the REST API for rendering templates which requires admin, the webhook API may not have the same requirements: https://developers.home-assistant.io/docs/api/native-app-integration/sending-data#render-templates.

**Comment by Skyslycer** [comment]
So odd. Is there a way to just retrieve the state of the sensor without rendering that within a template? What would the best approach be for fixing this, either here through some workarounds or bugging some HA developers?

**Comment by philipabbey** [comment]
We have an idea. We can swap the template HTTP calls to webhooks, which we are already using for some other bits of the functionality.

**Comment by Skyslycer** [comment]
That would be awesome!

**Comment by philipabbey** [comment]
Ref: https://developers.home-assistant.io/docs/api/native-app-integration/sending-data/#render-templates
