### ISSUE TITLE
GHA over Wi-Fi

### ISSUE THREAD

**Issue by philipabbey** [house-of-abbey/GarminHomeAssistant#142]
@brunoleon suggested it should be able to make the application work over Wi-Fi, see https://community.home-assistant.io/t/home-assistant-app-for-garmin/637348/270. Previously we have looked into this but not found a way. @brunoleon has provided some sample code at https://github.com/brunoleon/garmin-ha-wifi-test.

1. Evaluate the sample code, check it works on own Garmin Venu2.
2. Identify how this solution can be added to the Application (not Widget) version of GarminHomeAssistant.

**Comment by mortenmathiasen** [comment]
Awesome app, but it requires bluetooth connection. What is the status of supporting WiFi?

**Comment by philipabbey** [comment]
Not great. There's been a suggestion it can work, but so far we've not had any success. The "Sync" process over Wi-Fi is for sync'ing (e.g. FIT files), and is not immediately available for general HTTPS, not as far as we have found. This issue is dragging on, and too many people seem to believe because they have Wi-Fi on their watch this must be possible. We're still looking to see if we can hijack the sync process for HTTPS, but we'll need to take the whole process apart and see if we can pretent to be sync'ing. Then we may have to re-architect the App as there are multiple GET requests over Bluetooth that the App needs to work, and the Wi-Fi sync process has an overhead we can't afford more than once.

To be honest, the request is a bit of a nightmare presently

Wi-Fi has additional demands over Bluetooth, e.g. its more power hungry (discharging your watch battery), and I'm sceptical it will deliver the benefit people want and take dispproportionate effort to code.

**Comment by brunoleon** [comment]
I think that it might be wise to be able to explicitely enable wifi when you need it for a feature (I mean an option in the json config you profive to the app)

ex: I need a wifi fallback for opening my garage door, for updating a widget I don't care and prefer to save battery

**Comment by philipabbey** [comment]
Except you need to enable Wi-Fi to get the JSON config (unless cached). Again possible, but new failure modes to code around. The usually off nature of Wi-Fi makes for a quite different proposition. A re-design even.

**Comment by philipabbey** [comment]
I've finally got around to looking at this more closely. I've simplified the code, and removed a class. Here's a video of the transfer of a single file.

https://github.com/user-attachments/assets/81624bed-a044-42ff-8ffa-fd5890746343

This does pose a few questions about how to integrate Wi-Fi based HTTP GET & POST requests in the application as originally feared. Naively we could sync for each GET/POST request, but that's actually impractical since we start with the Webhook IDs, then move on to the menu, then the updates (which might be easier now we've moved to a single update request for all menu items), then we have to start a sync for each action, and then the next round of updates too.

Ideally we would start the transfer and keep the sync going for multiple requests, until the app is closed. That means covering the sync view up with the menu view over the top. Perhaps not impossible. And we have made the job easier for ourselves with v2.19 (single update request). Integration remains risky at best and potentially disruptive. Starting up a sync makes HTTP requests significantly laggy, but I expect those asking for the functionality are happy with that.

**Comment by philipabbey** [comment]
> Ideally we would start the transfer and keep the sync going for multiple requests, until the app is closed.

Now battling with differences between simulation and running on a real watch.

In simulation I can get the sync started, cover the sync progress view with a menu, click each item in the menu and get a response to update the menu item, then exit.

In real life I cannot get the sync view to be covered up by the menu with the items to click. Then when I press the back key, the sync stops leaving a menu with no Internet connection.

Tries:
1. WatchUi.popView(WatchUi.SLIDE_RIGHT) - Makes updates to the menu fail until thye menu is wiggled
2. WatchUi.pushView(..) - Works in Sim, but not on the device. Suggests that the SyncDelegate is required to complete then exit rather than hang around in the background.
3. WatchUi.switchToView(..) - Works in Sim, but not on the device. Suggests that the SyncDelegate is required to complete then exit rather than hang around in the background.

Starting a sync for each individual HTTP GET/POST will be annoying as several are required at the start (menu and status update) and then one for each status update there after, which will interrupt user interaction with the menu, and add a Wi-Fi search for each HTTP GET/POST.

Bored with this, the Garmin SDK clearly does not wish to be abused in this way.

**Comment by brunoleon** [comment]
Thanks a lot for spending time on this. I perfectly understand you got fed up by this.

I will (one day...) build a simple app to do this only one task which needs wifi for me, opening the garage door.  I'll post a link if anybody is interested.

**Comment by martin-snajdr** [comment]
Please do so!

Am Mo., 4. Nov. 2024 um 20:53 Uhr schrieb Bruno Leon <
***@***.***>:

**Comment by philipabbey** [comment]
> Thanks a lot for spending time on this. I perfectly understand you got fed up by this.
> 
> I will (one day...) build a simple app to do this only one task which needs wifi for me, opening the garage door. I'll post a link if anybody is interested.

You need to manage the HTTP GETs for the (optional) fetching of the menu, then the status updates (which are now managed with one request for all menu items, so easier) as well as the chosen action.

Good luck, I agree that it would be good for when I'm out of range of my mobile phone.
