### ISSUE TITLE
Activity Completed Background Update

### ISSUE THREAD

**Issue by JosephAbbey** [house-of-abbey/GarminHomeAssistant#149]
Aside from temporal events, the only useful trigger for background services is activity completion (https://developer.garmin.com/connect-iq/api-docs/Toybox/Background.html#registerForActivityCompletedEvent-instance_method).

Updating the states instantly on completion would allow for better automations:

- More reliable stop watch reminders.
- Trigger on completion.

We should be able to use the same callback that is already implemented for temporal events.

**Comment by philipabbey** [comment]
https://developer.garmin.com/connect-iq/api-docs/Toybox/System/ServiceDelegate.html#onActivityCompleted-instance_function

Have `onActivityCompleted()` call `onTemporalEvent()`?
- Factor out the code in `onTemporalEvent()` to allow for `sport` and `subsport` to be parameters.
- `onActivityCompleted()` supplies both parameters as `-1` for end of activity.
