### ISSUE TITLE
Can't open app with right swipe

### ISSUE THREAD

**Issue by krzysztofkub** [house-of-abbey/GarminHomeAssistant#159]
**Describe the bug**
On garmin venu 3 can't open app by creating right swipe shortcut. Screen is blank for a second but then closes. I have to do it couple of times then app starts successfully

**IMPORTANT!**
I have:

- [X] Used HTTPS to access HomeAssistant (with a public certificate)
- [X] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [X] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [X] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [X] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [X] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. Set up in watch settings shortcut to swipe right to app home assistant
2. Swipe right on clock face
3. Screen is going black for a second 
4. Screen is going back to watch face
5. Nothing more happens

**Expected behavior**
I'd expect that HA app will open

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://1drv.ms/v/c/78671589229263a6/ESVtmjIvTFtOhqpp5_PAADEBW5oRZqnBjLR1_zyeo4pxug?e=GOndxB)

**Garmin Device (please complete the following information):**

- Model: Venu 3

**Smartphone (please complete the following information):**

- Device: Samusng Galaxy S23

**Additional context**
It kind of work when I leave my finger on screen after swipe. All other apps on my watch work fine, only problem is HA app

**Comment by philipabbey** [comment]
We do not have the hardware to reproduce this issue. The description is alien to me as I don't recognise the "swipe right" functionality of the Venu 3 device. The application works just on Venu2 hardware and operates the same as that in the simulator.

Can you post a video to demonstrate the issue please?

**Comment by krzysztofkub** [comment]
https://www.youtube.com/watch?v=lDWGfoD3Qe8&ab_channel=HowTo
at 0:15 you can see shortcut menu. You can define action per each:
- middle button tap
- middle button hold
- right swipe

Also in my report, under **Screenshots** section I've added video of the issue, please check it

**Comment by philipabbey** [comment]
Superb and comprehensive video here. Thank you.

So the bottom line is, its just another means to start the HA app, no additional thrills from what I can see. Interesting that on my Venu 2, I have a single "swipe" shortcut but it can only work with a subset of the vendor apps (save location, music controller) and not with any user installed apps.

This leaves me in an awkward position. If the HA app works when invoked from a menu of apps, then its not obvious why it would not work when invoked any other way. It just has to start.

Nor does the simulator allow me to simulate this way of invoking the App that I can immediately see. I totally get why you would want this to work, I would. Unfortunately the crash reports that the device generates include insufficient detail to provide a lead on why the app may not have started. So I need more information to resolve this, but have no idea how to get it.

**Comment by krzysztofkub** [comment]
I'll try to investigate that further and maybe provide more details here. Would be nice if someone with venu 3 could check it if issue is more global.

Thanks for quick response

**Comment by philipabbey** [comment]
Silly questions (forgive me):
1. App still works when started other ways?
2. Other user apps start okay from ashortcut?

I've talked the Internet, and no clues that something special needs to be provided by the app, like for example with a glance.

**Comment by mwendle** [comment]
I had the same problem. Enabling the "cached configuration" fixed it.
Or if you swipe very slowly or even hold your finger halfway, the app has time to display some ui elements and it starts. If you lift your finger and the app is not displaying anything yet, it will close immediately. see video 

https://github.com/user-attachments/assets/6d76e9d9-18a1-4a6b-a3bd-54773cc88564

**Comment by philipabbey** [comment]
That implies there's a fix since its the fetching of the menu that is implicated. I assume that when opening the application with a slow swipe, there's more time to perform the HTTP GET of the JSON menu file. When using a fast swipe the application fails to have the menu ready. Its a clue, but does not explain why starting the application from a list of applications and activities still works, and the swipe does not.

Thank you for this information.

**Comment by philipabbey** [comment]
@krzysztofkub Please can you confirm if the advice from @mwendle worked for you? I appreciate it does not completely solve the problem.

**Comment by mwendle** [comment]
I haven't checked the issue for a while, but it no longer occurs for me. I tested it throughout the day with no problems (cached configuration disabled). I don't know exactly which update fixed it or whether it was an update to the watch itself. Maybe someone can verify whether the bug has been fixed.
