### ISSUE TITLE
Make loading screen when waiting for http response when app opens

### ISSUE THREAD

**Issue by krzysztofkub** [house-of-abbey/GarminHomeAssistant#160]
**Is your feature request related to a problem? Please describe.**
It's annoying that when I open app I can see default initial state of my switches, then http response with state comes and switches are changing

**Describe the solution you'd like**
Make loading screen and load switches state only when response comes

**Comment by philipabbey** [comment]
The updates are based on a "round robin" state fetch. This is a constraints within which the design operates. The watch app needs to be responsive t external changes, e.g. by the phone app. What you are suggesting would mean:
1. A very long time for the initial display of the menu, such that users might think the app is broken.
2. When would you update the display for external changes (e.g. via web browser)?

See https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/README.md#external-device-changes

> Make loading screen and load switches state only when response comes

Its not one response but many individual ones. The separate responses are necessary.

Without a fundamental redesign, and probably some changes to the way HA services API calls, this is not going to happen.

**Comment by krzysztofkub** [comment]
maybe don't show switch icon until you know the state of that switch?

**Comment by philipabbey** [comment]
The Connect IQ API does not give developers that level of control.

At the end of the day, its just a small watch app that covers a fraction of what the HA App or Web GUI can do, so it will always be inferior and limited by comparison.

**Comment by philipabbey** [comment]
Related and probably good enough is https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/ToggleMenuItem.html#setEnabled-instance_function

So items can be disabled until they are first updated. That will prevent the toggle menu item toggling until after it has been updated, which gives me misgivings about it being a good idea.
