### ISSUE TITLE
Templating & content for all types

### ISSUE THREAD

**Issue by mcsdodo** [house-of-abbey/GarminHomeAssistant#165]
### Discussed in https://github.com/house-of-abbey/GarminHomeAssistant/discussions/148

Would it be possible to add templating possibilities for all types. Let's say I have a group, there are multiple lights in it. On the top view (when navigating items) I would like to have the "content" so I can check my custom state.

**Comment by philipabbey** [comment]
We likw this idea and see how it could be done. Just need to do it now!

**Comment by philipabbey** [comment]
Sorry if this seems like an obvious question, but how would you use a toggle with a template text?

**Comment by mcsdodo** [comment]
I can think of some (but will be specific to my smart home/plans):
1. you would want to see brightness level of a light
2. see number of people in your house when arming alarm system
3. see humidity level in your garage when turning on exhaust fan
