### ISSUE TITLE
App v2.16 breaks on Forerunner 55 with IQ(!) screen

### ISSUE THREAD

**Issue by denisfrench** [house-of-abbey/GarminHomeAssistant#166]
**Describe the bug**
The GHA app (I'm not using the widget) was working great on my Forerunner 55, then broke when updated to v2.16, showing the IQ(!) screen upon launching.

**IMPORTANT!**
I have:

- [x] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. GHA app v2.15 (I think) was working fine on my Forerunner 55.
2. Update to v2.16 using Connect IQ on Forerunner 55.
3. No other changes were made.
4. Open the app menu, and launch the GHA app.
5. The menu flashes up very briefly, then the IQ(!) screen shows.

**Expected behavior**
I expected the GHA app to be even more awesome, since it was working great before the update.

**Screenshots**
N/A

**Garmin Device (please complete the following information):**

- Model: Forerunner 55

**Smartphone (please complete the following information):**

- Device: Doogee S96GT
- OS: Android 12

**Additional context**
I have also tried:
- Restarting my watch.
- Uninstalling and reinstalling the GHA app.
- Reducing the size of my .json file by about a third.
- Restarting Home Assistant.
- The troubleshooting button within the online json editor (all okay).

Please Make this App Great Again 😀

**Comment by philipabbey** [comment]
Thank you for reporting this.

**Comment by philipabbey** [comment]
The error is reproducable:

```
Error: Symbol Not Found Error
Details: Could not find symbol 'floorsClimbed'
Stack: 
  - registerWebhookSensors() at A:\Philip\Programming\MonkeyC\HomeAssistant\source\WebhookManager.mc:213 0x100035a6 
  - onReturnRequestWebhookId() at A:\Philip\Programming\MonkeyC\HomeAssistant\source\WebhookManager.mc:72 0x10002b77 

Encountered app crash.
```

I have something to go on.

**Comment by philipabbey** [comment]
https://developer.garmin.com/connect-iq/api-docs/Toybox/ActivityMonitor/Info.html#floorsClimbed-var

We've not fallen foul of any API level requirements. Looks like it is insufficient to test `activityInfo.floorsClimbed == null`. In fact, when a device is not supported, that field does not exist to be tested, hence the error.

@KPWhiver FYI

**Comment by KPWhiver** [comment]
> https://developer.garmin.com/connect-iq/api-docs/Toybox/ActivityMonitor/Info.html#floorsClimbed-var
> 
> We've not fallen foul of any API level requirements. Looks like it is insufficient to test `activityInfo.floorsClimbed == null`. In fact, when a device is not supported, that field does not exist to be tested, hence the error.
> 
> @KPWhiver FYI

I can add the necessary "has" statements if you want? I'll have to setup a forerunner 55 simulator though.

**Comment by philipabbey** [comment]
I think I've got the required fixes lined up now. Stand by to review the changes.

**Comment by philipabbey** [comment]
@denisfrench Thank you for your constructive feedback via Github and for not using the Garmin app store's review mechanism to post a poor review. There should be a v2.17 available later today.
