### ISSUE TITLE
Received invalid webhook payload: value must be at least 0 for dictionary

### ISSUE THREAD

**Issue by MG-Sky** [house-of-abbey/GarminHomeAssistant#168]
**Describe the bug**
error from hass:

Received invalid webhook payload: value must be at least 0 for dictionary value @ data['course']. Got -1

**IMPORTANT!**
I have:

- [x ] Used HTTPS to access HomeAssistant (with a public certificate)
- [x ] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x ] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x ] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [ x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [ x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**
i dont know how 
**Expected behavior**

**Screenshots**

**Garmin Device (please complete the following information):**

- Model: [e.g. Venu 2]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by philipabbey** [comment]
@KPWhiver I might need your insight here as it appears to be a complaint from Home Assistant, and perhaps related to this bit of code at https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/source/BackgroundServiceDelegate.mc#L113.

I have a Venu 2 watch as well, which is working well.

**Comment by philipabbey** [comment]
So there is an annoyance with the simulator described at https://forums.garmin.com/developer/connect-iq/f/discussion/2571/position---info---heading. The simulator cannot set the heading value, which would have been useful to determine the range of expected values since clearly they are different to currently observed device experiments.

**Comment by philipabbey** [comment]
https://developer.garmin.com/connect-iq/api-docs/Toybox/Position/Info.html
![image](https://github.com/user-attachments/assets/9883e260-7e52-44bb-8c36-fac97323bf6a)

Guess it returned a `Null` then.

**Comment by KPWhiver** [comment]
I would have expected some kind of null reference error in that case, no clue how it would go from null to -1. It would e a good idea nonetheless to check for null.

**Comment by KPWhiver** [comment]
As for the Home Assistant part, it simply requires that the course is a positive integer (https://github.com/home-assistant/core/blob/7c8e00e5e062ced0820ab9f777b23e531f668e47/homeassistant/components/mobile_app/webhook.py#L419) and so this error is raised.

**Comment by philipabbey** [comment]
> value must be at least 0

So ≥0

> requires that the course is a positive integer

So > 0?

I'm guessing by `postitive_in` they really mean unsigned int and that zero really is included!

I've got some `null` checking implemented, but this error is not simulatable so we're just guessing and hoping.

**Comment by KPWhiver** [comment]
Sorry for the confusion, the value should be: ≥0 (https://github.com/home-assistant/core/blob/7c8e00e5e062ced0820ab9f777b23e531f668e47/homeassistant/helpers/config_validation.py#L184)

**Comment by MG-Sky** [comment]
yesterday I have updated to newest avail. in store but today in Hass (i have venu 2)
Received invalid webhook payload: value must be at least 0 for dictionary value @ data['course']. Got -52
Received invalid webhook payload: value must be at least 0 for dictionary value @ data['course']. Got -2
Received invalid webhook payload: value must be at least 0 for dictionary value @ data['course']. Got -87
Received invalid webhook payload: value must be at least 0 for dictionary value @ data['course']. Got -76
Received invalid webhook payload: value must be at least 0 for dictionary value @ data['course']. Got -79

**Comment by philipabbey** [comment]
Thank you, the guess we tried was clearly not right. Now its obvious there's a range of negative values getting in, so some addition to a positive range must be necesssry not just a check for null.

**Comment by MG-Sky** [comment]
if i can help somehow, let me know

**Comment by philipabbey** [comment]
Please update to v2.20 and recheck.

**Comment by MG-Sky** [comment]
yes, now i dont see such events in hassOd: Philip Abbey ***@***.***>Wysłano: sobota, sierpnia 31, 2024 1:01:53 PMDo: house-of-abbey/GarminHomeAssistant ***@***.***>DW: MG-Sky ***@***.***>; Author ***@***.***>Temat: Re: [house-of-abbey/GarminHomeAssistant] Received invalid webhook payload: value must be at least 0 for dictionary (Issue #168)
Please update to v2.20 and recheck.
