### ISSUE TITLE
Nabu casa connection?

### ISSUE THREAD

**Issue by siggmur** [house-of-abbey/GarminHomeAssistant#18]
I'm getting error code = 0. Assuming it's a nabu casa issue which I know more people are having (again, assumed). 

Any inputs for nabu casa users?

**Comment by philipabbey** [comment]
See here, https://community.home-assistant.io/t/home-assistant-app-for-garmin/637348/23, and my reply.

Please use that forum for support so that others my beenfit fro the discussion. Has this has been resolved?

**Comment by siggmur** [comment]
Thanks for reaching out. I didn't get it fixed no, I really haven't tested too much other than what was posted though. But if I find a fix I will for sure post it!
________________________________

**Comment by philipabbey** [comment]
@siggmur just checking in. We've created our own free Nabu Casa account to see what the issues are with setting up this app. We created the following troubleshooting page at https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/Troubleshooting.md. We found the Nabu Casa setup straightforward. If you are still struggling, please can you check that page out and let us know if it was helpful?

**Comment by siggmur** [comment]
@philipabbey I tried today. I needed to resync connec IQ with my watch. And for some reason it now works. Thanks for getting back to me, and thanks for making this app!

**Comment by philipabbey** [comment]
Issue resolved.
