### ISSUE TITLE
Templated content truncated on FR55

### ISSUE THREAD

**Issue by denisfrench** [house-of-abbey/GarminHomeAssistant#180]
**Describe the bug**
Template output appears to be truncated, despite more room available on the screen.

**IMPORTANT!**
I have:

- [x] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. Insert a templated state entry into the json file as follows:
```
{
  "name": "TEST",
  "type": "template",
  "content": "0123456789"
}
```
2. Open GHA app on watch

**Expected behavior**
0123456789 should be displayed without scrolling or being truncated, unless the screen is not wide enough.

**Observed behavior**
0123456 appears (cut off through the 6), scrolls to the end, then reverts to 0123456.
Nearly half the screen is still available to the right of 0123456.

**Screenshots**
![IMG_20240831_180225_090](https://github.com/user-attachments/assets/dfef1ca3-f8db-449d-8e2d-ddab6dd6ea58)

**Garmin Device (please complete the following information):**

- Model: FR55

**Smartphone (please complete the following information):**

- Device: Doogee S86GT
- OS: Android 12

**Additional context**
Maybe this is a limit of the watch or the SDK, but if not it would be ideal to use the entire width of the screen before truncating the template output.

**Comment by philipabbey** [comment]
Great test and demo. The only problem is we do not control the width of the text displayed. We call the [setSubLabel()](https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/MenuItem.html#setSubLabel-instance_function) function. Width is managed by that class. We do control the alignment, which you can vary in the GHA Application options. This sub title display shortening does not happen on a Venu 2 or Vivoactive 3 device, and hence it sounds device specific with no opportunity to amend for Forerunner 55 devices.

I'm guessing this is where our application is pushing the limits of some available devices?

**Comment by denisfrench** [comment]
VA3 was my last watch. I realise the FR55 is a low-end watch, but it surprises me that function appears to have regressed since older watches.

Is there somewhere I can submit a bug report with Garmin?

**Comment by philipabbey** [comment]
To give you some idea what the simulator shows:

![fr55](https://github.com/user-attachments/assets/c6700abf-10f6-41f5-88cf-de56f7d8f454)

No truncation here, but it is usual for the simulator to not quite reflect the actual watch layout.

As for support, I've been searching the Internet briefly. I'll get back to you on that one, it appears that content in the help pages depends on the language used for display. You might get a Chat or Email option, you might get nothing.

**Comment by philipabbey** [comment]
Leads on submitting bug reports are not looking hopeful:

- [Where do you report bugs to Garmin?](https://forums.garmin.com/sports-fitness/running-multisport/f/forerunner-965/330655/where-do-you-report-bugs-to-garmin)
- [What is the best way to report a bug?](https://forums.garmin.com/outdoor-recreation/outdoor-recreation/f/epix-2/316009/what-is-the-best-way-to-report-a-bug)
- [Bug reporting](https://forums.garmin.com/developer/connect-iq/f/discussion/4767/bug-reporting)
- [Connect IQ > Connect IQ Bug Reports](https://forums.garmin.com/developer/connect-iq/i/bug-reports), see [FAQ](https://forums.garmin.com/developer/connect-iq/w/wiki/5/bug-reports-faq)

There are more search results, but it dow sound like people are frustrated with the whole bug reporting process. So I don't hold out much hope for you successfully getting through.

**Comment by denisfrench** [comment]
Thanks for the leads.

Given the lack of responsiveness, probably a wasted effort to report an isolated bug on a watch that is approaching end of life.

Thanks for looking into it anyway 🙂
