### ISSUE TITLE
Tap confirmation toast does not disappear without user intervention

### ISSUE THREAD

**Issue by denisfrench** [house-of-abbey/GarminHomeAssistant#181]
**Describe the bug**
The readme (https://github.com/house-of-abbey/GarminHomeAssistant?tab=readme-ov-file#tap-item-response) states the tap item confirmation toast will disappear after a short while if not dismissed by the user, however it seems to remain unless a button is pressed.

**IMPORTANT!**
I have:

- [x] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [x] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. Activate tap item.
2. Confirmation toast appears.
3. Wait for toast to disappear.
4. Application times out before toast disappears (timeout currently set to 30s).

**Expected behavior**
The toast should disappear promptly, rather than adding to the required button presses to exit the app (currently 3 presses).

**Screenshots**
N/A

**Garmin Device (please complete the following information):**

- Model: FR55

**Smartphone (please complete the following information):**

- Device: Doogee S96GT
- OS: Android 12

**Additional context**
The great utility of this watch app is to switch simple entities very quickly without reaching for your phone. Any increase in delay or button presses detracts from this; I suggest the toast really only needs to remain for 1-2s.

Thanks for your work on this awesome app 😀

**Comment by philipabbey** [comment]
This is a real problem, since there is no API call to remove the toast. The [showToast()](https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi.html#showToast-instance_function) documentation gives no additional call to remove it. So the only recourse we have it to not show confirmation via a toast at all, for all devices for all users.

**Comment by denisfrench** [comment]
I'm not sure if this actually tests the toast function, but message and GPS notifications do disappear quickly within the native run app.

If this isn't a valid test, could you point me to an app I can properly test the toast function with?

**Comment by philipabbey** [comment]
Sounds like a valid test. On a Venu 2 inside the GHA App, a 'toast' can take 15 seconds to dissappear.

**Comment by philipabbey** [comment]
So the options are:
1. Leave the functionality unchanged, accept the need to manually dismiss a 'toast'.
2. Remove the display of a toast for all (devices & users).

In the meantime I have amended the documentation at https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/README.md#tap-item-response.

**Comment by denisfrench** [comment]
Fair enough; thanks for investigating anyway 🙂
