### ISSUE TITLE
Add support for the latest devices released from Garmin

### ISSUE THREAD

**Issue by philipabbey** [house-of-abbey/GarminHomeAssistant#182]
Check for new devices and amend the `manifest.xml` file. At least the Fenix 8* devices are missing, but there may be others on the list at https://developer.garmin.com/connect-iq/compatible-devices/.

**Comment by philipabbey** [comment]
The new devices are:
- edge1050
- enduro3
- fenix843mm
- fenix847mm
- fenix8solar47mm
- fenix8solar51mm
- fenixe

**Comment by philipabbey** [comment]
None of the edge devices support [ActivityMonitor](https://developer.garmin.com/connect-iq/api-docs/Toybox/ActivityMonitor.html). This means the recent addition of this extra information has broken all Edge devices.

**Comment by Orkote** [comment]
Thanks a lot, Philip! If you need to check anything on the Fenix 8, drop me a line!

**Comment by ianroakes** [comment]
Looking forward to compatibility for Fenix 8 - it was one of the first things I checked when setting up my new watch. Also have a Fenix 8 handy if you need anything!

**Comment by philipabbey** [comment]
edge1050 - same issue as Edge 540 and Edge 840 devices, see [Known Issues](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/README.md#known-issues).
enduro3 - tested
fenix843mm - tested
fenix847mm - tested
fenix8solar47mm - tested
fenix8solar51mm - tested
fenixe - tested

SDK updated to 7.3.0 in order to get new devices to work in simulation.

**Comment by philipabbey** [comment]
@Orkote & @ianroakes Please can you check out v2.21 at https://apps.garmin.com/apps/61c91d28-ec5e-438d-9f83-39e9f45b199d. I would appreciate confirmation you have a working app on your watches now. Thanks!

**Comment by ianroakes** [comment]
Installed and setup, confirming it works exactly as expected! Thanks for updating this so quickly. 
![photo_2024-09-06 13 03 43](https://github.com/user-attachments/assets/98056abd-a38c-4e4b-9d74-7a201c389f70)
![photo_2024-09-06 13 03 39](https://github.com/user-attachments/assets/44637855-7d9d-4f2c-84f1-f5f1c163f321)

**Comment by Orkote** [comment]
Working like a charm also for me!

![IMG_8025](https://github.com/user-attachments/assets/59dcfb1d-53b1-4026-beb5-f80b445ca160)
