### ISSUE TITLE
Allow confirming switch toggle

### ISSUE THREAD

**Issue by pedropombeiro** [house-of-abbey/GarminHomeAssistant#190]
**Is your feature request related to a problem? Please describe.**
I have a toggle switch that turns on/off my TV. Sometimes I hit the wrong button and the TV turns off, which doesn't go well with the family.

**Describe the solution you'd like**
I'd like a confirmation before the action.

**Describe alternatives you've considered**
I considered moving this to a `switch.toggle` action, but then I'd lose the switch current status.

**Comment by JosephAbbey** [comment]
We do support confirmations on toggle items.

https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/source%2FHomeAssistantToggleMenuItem.mc#L215-L229

**Comment by JosephAbbey** [comment]
And in the schema:

https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/config.schema.json#L38-L40

**Comment by JosephAbbey** [comment]
Inside `tap_action`, set `confirmation` to `true`:

```json
{
  "type": "toggle",
  ...,
  "tap_action": {
    "confirmation": true
  }
}
```

**Comment by pedropombeiro** [comment]
Ah, I just needed to create a `tap_action` (which I was missing before). Thanks for the pointer!

**Comment by philipabbey** [comment]
I think the action here is to amend the documentation to make this obvious, e.g. on the example page.

**Comment by philipabbey** [comment]
https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/examples/Switches.md has been amended to be explicit.
