### ISSUE TITLE
Mini-circle screen bugs out on certain items

### ISSUE THREAD

**Issue by ericswpark** [house-of-abbey/GarminHomeAssistant#191]
On certain menu items, the mini-circle screen on my Garmin Instinct 2X bugs out completely and displays a garbled image. This goes away if I go to another menu. I'm not sure whether there are any other adverse effects, but I haven't noticed them. (The app closed once but I'm unable to reproduce and I think it may have been the auto-timeout that I set.)

I've noticed this with the template type and the scene type so far.

See photo:

![20241006_111231](https://github.com/user-attachments/assets/1d75b021-78e2-4076-aceb-06ad6450f4a2)

**Comment by philipabbey** [comment]
Like this? https://github.com/house-of-abbey/GarminHomeAssistant/issues/132

I direct you to the closing remark at https://github.com/house-of-abbey/GarminHomeAssistant/issues/132#issuecomment-2335143267

> I'm closing this issue as the problem is too specific to a few devices and not general. The fix looks involved, so I'm just going to suggest you wait until you upgrade your watch for a newer model. Sorry that's not ideal.

Garmin did not do us any favours with the watch face design! Sorry.

**Comment by ericswpark** [comment]
Yeah, that seems to be the problem. Won't it continue to be an issue on certain watch lineups like the Instinct line where the screen will probably continue to be BW-only?

**Comment by philipabbey** [comment]
> Won't it continue to be an issue on certain watch lineups like the Instinct line where the screen will probably continue to be BW-only?

Forever! But the discriminant is not "BW-only", its the messy icon usage.

> Alternatively could the icon just not be shown at all on unsupported devices?

Again I'll refer you to the same previous issue, see [this comment](https://github.com/house-of-abbey/GarminHomeAssistant/issues/132#issuecomment-2040314133).

The problem is too expensive to fix for too few watches. I've not even got a technical solution. Like I said, Garmin did not do us any favours.

**Comment by ericswpark** [comment]
Okay, thank you for the explanation. Closing this issue
