### ISSUE TITLE
Steps shown in HA as string (no grapth)

### ISSUE THREAD

**Issue by MG-Sky** [house-of-abbey/GarminHomeAssistant#195]
**Describe the bug**
In HA Steps are shown as string:
<img width="458" alt="image" src="https://github.com/user-attachments/assets/5d6d502f-ab01-4a2c-9235-895e70a5ce84">

also in statistics i see 'fix' for a some entities of your  app:
<img width="736" alt="image" src="https://github.com/user-attachments/assets/26fd6246-3d18-47a3-bcaf-3b05311ebade">

**To Reproduce**

1. Go to '...' Statistics / steps today entity
2. Click on '....' display history see the bar instead of graph (or fix the entity in statistics)

**Expected behavior**

steps today should be an Int (i believe right now HA thinks it's a string?)
class state should be fixed  for entities, if possible

**Screenshots**

**Garmin Device (please complete the following information):**

- Model: [e.g. Venu 2] Venu 2s

**Additional context**

**Comment by philipabbey** [comment]
I get something more like this:

![image](https://github.com/user-attachments/assets/fa54bfdb-9335-432a-bb81-690a1cfb8e26)

Is it worth removing your garmin device and all the senors and re-running the Garmin HA app to re-create the Webhooks?

**Comment by MG-Sky** [comment]
yes I've been thinking something is wrong on my side, perhaps some db entry isnt an int. Will check this. thank you for this appOd: Philip Abbey ***@***.***>Wysłano: czwartek, listopada 7, 2024 6:51:27 PMDo: house-of-abbey/GarminHomeAssistant ***@***.***>DW: MG-Sky ***@***.***>; Author ***@***.***>Temat: Re: [house-of-abbey/GarminHomeAssistant] Steps shown in HA as string (no grapth) (Issue #195)
I get something more like this:
image.png (view on web)
Is it worth removing your garmin device and all the senors and re-running the Garmin HA app to re-create the Webhooks?

**Comment by philipabbey** [comment]
@MG-Sky Has this been resolved?

**Comment by philipabbey** [comment]
Thanks for the reply.
