### ISSUE TITLE
Tap or toggle don't work on venu 2

### ISSUE THREAD

**Issue by Patrick44fr** [house-of-abbey/GarminHomeAssistant#2]
Hello,
First of all, congratulations on your work which is the most accomplished of what I have tested.

I followed the procedure and my watch (Venu2) displays the entities that I configured.

But I cannot send a command, neither "tap" nor "toggle"

I tested my **long live token** with a rest_command and it 's correct.

Can you help me
 Thanks
sorry for my bad english. I am French.

my json config: (ihave changed my entities for security)
`{
  "$schema": "https://raw.githubusercontent.com/house-of-abbey/GarminHomeAssistant/main/config.schema.json",
  "title": "Domicile",
  "items": [
    {
      "entity": "script.script_ring_desactivation_alarmemaison",
      "name": "Arret Alarme",
      "type": "tap"
    },
    {
      "entity": "switch.tasmota10",
      "name": "Basc. Porte garage",
      "type": "toggle"
    },
    {
      "entity": "switch.tasmota30",
      "name": "Ambiance1 Salon",
      "type": "toggle"
    },
    {
      "entity": "menu.eclairage_salon",
      "name": "Eclairage Salon",
      "title": "Salon",
      "type": "group",
      "items": [
        {
          "entity": "light.halogenes4",
          "name": "Halogene",
          "type": "toggle"
        },
        {
          "entity": "light.lamp_leds",
          "name": "Lampe Led",
          "type": "toggle"
        },
        {
          "entity": "light.lampe_phones",
          "name": "Lampe téléphone",
          "type": "toggle"
        }
      ]
    },
    {
      "entity": "script.script_lampe_couleur_pou_raz",
      "name": "RAZ Lampe",
      "type": "tap"
    },
    {
      "entity": "switch.crnr_tbl_usbs",
      "name": "Corner Table USBs",
      "type": "toggle"
    }
  ]
}`

**Comment by philipabbey** [comment]
Just to acknowledge your submission.

```json
{
  "$schema": "https://raw.githubusercontent.com/house-of-abbey/GarminHomeAssistant/main/config.schema.json",
  "title": "Domicile",
  "items": [
    {
      "entity": "script.script_ring_desactivation_alarmemaison",
      "name": "Arret Alarme",
      "type": "tap"
    },
    {
      "entity": "switch.tasmota10",
      "name": "Basc. Porte garage",
      "type": "toggle"
    },
    {
      "entity": "switch.tasmota30",
      "name": "Ambiance1 Salon",
      "type": "toggle"
    },
    {
      "entity": "menu.eclairage_salon",
      "name": "Eclairage Salon",
      "title": "Salon",
      "type": "group",
      "items": [
        {
          "entity": "light.halogenes4",
          "name": "Halogene",
          "type": "toggle"
        },
        {
          "entity": "light.lamp_leds",
          "name": "Lampe Led",
          "type": "toggle"
        },
        {
          "entity": "light.lampe_phones",
          "name": "Lampe téléphone",
          "type": "toggle"
        }
      ]
    },
    {
      "entity": "script.script_lampe_couleur_pou_raz",
      "name": "RAZ Lampe",
      "type": "tap"
    },
    {
      "entity": "switch.crnr_tbl_usbs",
      "name": "Corner Table USBs",
      "type": "toggle"
    }
  ]
}
````

Checks out in the schema checker (you already knew that). You mention working API key and that the menu does display on your Venu2 (same device as me, so this is the most tested!). As you are getting no actions working, I'm going to go with API URL. Please can you re-test your REST command with a copy & paste of your API URL from your watch settings?

Otherwise the next step would be to screen share somehow so I can get a better feel for what's going on here as I'm worried. This should be working.

**Comment by philipabbey** [comment]
Another thought. Does your set up meet this requirement from the README.md?

_"It is important to note that your Home Assistant instance will need to be accessible via HTTPS with public SSL or all requests from the Garmin will not work. This cannot be a self-signed certificate, it must be a public certificate (You can get one for free from [Let's Encrypt](https://letsencrypt.org/) or you can pay for [Home Assistant cloud](https://www.nabucasa.com/))."_

 I've missed an opportunity for some error checking on API URLs. That I can fix.

**Comment by Patrick44fr** [comment]
Hello, thank you for your answer, I did some research on my installation, tested the curl for the token, everything is ok and I use a let's encrypt certificate.

when consulting the NGINX proxy manager logs, I noticed that there was a double slash behind api.

I removed the slah in the API settings by putting:
`https://<homeassistant>/api`

It seems that the error is in the readme, the slash is present .
`2 Add the URL for your Home Assistant API, e.g. https://<homeassistant>/api/.`

all switches and lights work, it's fine.

automations and scripts do not respond to tap, and do not appear in NGINX logs.
I continue my research...

![nginx](https://github.com/house-of-abbey/GarminHomeAssistant/assets/74200895/4793b0ce-7fb9-4f90-837d-aa93e13396c5)

**Comment by philipabbey** [comment]
README.md will be amended, thank you for your insights. Good work.

**Comment by Patrick44fr** [comment]
Good morning,
here is the progress of my various tests:

- for scenes, with 'tap' option and service (scene.turn_on) everything works correctly, there is an execution message on the watch.

- for scripts, with 'tap' option without service does not work but works well with service (script.turn_on), there is an execution message on the watch.

- for automation, with the 'tap' option without service does not work, however it works well with service (automation.trigger), there is no execution message on the watch.

in the case of automations, I was not able to test with automation.turn_on, I do not know how to trigger the reception of the command by API. Maybe I didn't understand the principle well.

If it is feasible, an example would allow me to better understand and increase the processing possibilities.

If I can give my opinion, the new service option is really great, it allows you to personalize via known commands in HOME ASSISTANT.

I'm going to highlight this project on the Home Assistant French forum.

Thank you for everything,
Sincerely.

**Comment by philipabbey** [comment]
> for automation, with the 'tap' option without service does not work, however it works well with service (automation.trigger), here is no execution message on the watch.

```shell
curl -s -X POST \
  -H "Authorization: Bearer ${API_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"entity_id": "automation.turn_off_usbs"}' \
  ${URL}/services/automation/trigger \
  | jq .
```

Returns the empty JSON array `[]`. Presently I check for an item in the returned array with the desired entity name as part of the confirmation. It should be an array of things that changed, e.g. for a scene. So as the array is empty, the condition to acknowledge is not met by the present code.

**Comment by philipabbey** [comment]
I'm looking to close this issue withthe following changes:

1. All taps must have a `service` tag. This will be a breaking change so will be done in two parts: firstly to change the schema to prompt people to amend their menus, in a later edition the application will ignore menu items without a service tag.
2. Implement acknowledgement of automations. These are now able to be both 'toggle's and 'tap's. (Previously they were just 'toggle's)

I hope that meets your expectations @Patrick44fr.
