### ISSUE TITLE
Sensor readings as text display

### ISSUE THREAD

**Issue by kortgat** [house-of-abbey/GarminHomeAssistant#26]
Hi, would it be possible to display basic sensor data, ex solar panel output from my inverter, or utility power on/off status?

**Comment by philipabbey** [comment]
There's been a previous post requesting something similar here: https://community.home-assistant.io/t/home-assistant-app-for-garmin/637348/20, perhaps worth using the HA forum to home in more precisely on what might be involved? Then post a firm proposal here.

E.g. what's the JSON format look like? How closely does that map to HA YAML fields?

**Comment by JosephAbbey** [comment]
This would mean that you can render a temperature with `"{{ states('sensor.my_temperature') }}°C"` or a battery as `"{{ states('sensor.my_battery_level') }}%"`.

I have been having some fun with the android version of this feature [here](https://community.home-assistant.io/t/battery-widget).

**Comment by JosephAbbey** [comment]
[Docs](https://developers.home-assistant.io/docs/api/rest/)

POST to

```
https://<homeassistant>/api/template
```

with

```json
{
    "template": "Paulus is at {{ states('device_tracker.paulus') }}!"
}
```

Returns the rendered template in **_plain text_**.

```
Paulus is at work!
```

Sample curl command:

```shell
curl -s -X POST \
  -H "Authorization: Bearer ${API_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"template": "It is {{ now() }}!"}' ${URL}/template
```

Response:

```
It is 2024-01-12 18:48:40.429751+00:00!
```
