### ISSUE TITLE
Error -400 - what did I do wrong?

### ISSUE THREAD

**Issue by Aaroneisele55** [house-of-abbey/GarminHomeAssistant#27]
Hello,
I found this app and I would really like to use it on my Venu 2.
When I then created the JSON file and entered all required data into the settings on the phone, I started the app on the watch and got Error Code -400.
What could I have done wrong?
![20231205_170945](https://github.com/house-of-abbey/GarminHomeAssistant/assets/87670899/0c367a8c-1ab6-4865-b791-623c3c421ae5)
Best regards
Aaron Eisele

**Comment by JosephAbbey** [comment]
Hi, just to check, have you edited the JSON file with the checking (in VSCode)?
This is likely a syntax error in your JSON.
If you need further help please provide us with a copy of your JSON config.

Thanks.

**Comment by Aaroneisele55** [comment]
> Hi, just to check, have you edited the JSON file with the checking (in VSCode)?
> This is likely a syntax error in your JSON.
> If you need further help please provide us with a copy of your JSON config.
> 
> Thanks.

Thanks for your help, here is my JSON:

`{ "$schema": "https://raw.githubusercontent.com/house-of-abbey/GarminHomeAssistant/main/config.schema.json", "title": "Home", "items": [{ "entity": "light.Esszimmer", "name": "Esszimmer Licht", "type": "toggle" }, { "entity": "menu.each_lounge_light", "name": "Esszimmerlichter", "title": "Esszimmer", "type": "group", "items": [ { "entity": "light.esszimmer_1", "name": "Esszimmer 1", "type": "toggle" }, { "entity": "light.esszimmer_2", "name": "Esszimmer 2", "type": "toggle" }, { "entity": "light.esszimmer_3", "name": "Esszimmer 3", "type": "toggle" }, { "entity": "light.esszimmer_4", "name": "Esszimmer 4", "type": "toggle" } ] } { "entity": "menu.aaron", "name": "Lichter Aaron", "title": "Aaron", "type": "group", "items": [ { "entity": "light.iris", "name": "Iris", "type": "toggle" }, { "entity": "light.kugel", "name": "Kugel", "type": "toggle" }, { "entity": "light.stehlampe", "name": "Stehlampe", "type": "toggle" }, { "entity": "light.wled", "name": "LEDs", "type": "toggle" }, { "entity": "light.aaron", "name": "Aaron", "type": "toggle" } ] } ] }`

**Comment by JosephAbbey** [comment]
Hi, I have found the issue.

```diff
{
  "$schema": "https://raw.githubusercontent.com/house-of-abbey/GarminHomeAssistant/main/config.schema.json",
  "title": "Home",
  "items": [
    {
      "entity": "light.Esszimmer",
      "name": "Esszimmer Licht",
      "type": "toggle"
    },
    {
      "entity": "menu.each_lounge_light",
      "name": "Esszimmerlichter",
      "title": "Esszimmer",
      "type": "group",
      "items": [
        {
          "entity": "light.esszimmer_1",
          "name": "Esszimmer 1",
          "type": "toggle"
        },
        {
          "entity": "light.esszimmer_2",
          "name": "Esszimmer 2",
          "type": "toggle"
        },
        {
          "entity": "light.esszimmer_3",
          "name": "Esszimmer 3",
          "type": "toggle"
        },
        {
          "entity": "light.esszimmer_4",
          "name": "Esszimmer 4",
          "type": "toggle"
        }
      ]
+    },
-    }
    {
      "entity": "menu.aaron",
      "name": "Lichter Aaron",
      "title": "Aaron",
      "type": "group",
      "items": [
        {
          "entity": "light.iris",
          "name": "Iris",
          "type": "toggle"
        },
        {
          "entity": "light.kugel",
          "name": "Kugel",
          "type": "toggle"
        },
        {
          "entity": "light.stehlampe",
          "name": "Stehlampe",
          "type": "toggle"
        },
        {
          "entity": "light.wled",
          "name": "LEDs",
          "type": "toggle"
        },
        {
          "entity": "light.aaron",
          "name": "Aaron",
          "type": "toggle"
        }
      ]
    }
  ]
}
```

Please use [VSCode](https://vscode.dev) to edit your configuration, that will find syntax errors like this as well as schema errors.
