### ISSUE TITLE
Feature Request for open/close covers

### ISSUE THREAD

**Issue by michaelwingender** [house-of-abbey/GarminHomeAssistant#4]
Hi,
I just found this project and successfully configured it for my Fenix 7. It is just working fine. Thanks a lot!

I hope it is OK to submit a feature request. I would like to control some covers and it would be great to open or close a cover using my watch. Do you think it is possible to add this?

BR
Michael

**Comment by philipabbey** [comment]
Hello!

Please can you start by trying to configure a toggle on a service? I would need more information on how your cover is configured to be able to comment further.

I appreciate the on/off text might not be what you want,  but it will be a start.

**Comment by philipabbey** [comment]
Would you be able to provide:
1. the API call required to effect your cover action? In Bash, this might look like:
```shell
curl -s -X POST \
  -H "Authorization: Bearer ${API_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"entity_id": "automation.turn_off_usb_chargers"}' \
  ${URL}/services/automation/trigger
```
But substitute the service or scene as appropriate and the entity ID (well text pattern at least).

Or

2. Or perhaps the entity ID (text pattern) so that we can try and guess the API call required.

**Comment by philipabbey** [comment]
https://www.home-assistant.io/integrations/cover/ suggests the following might work out of the box today:

```json
    {
      "entity": "cover.patio",
      "name": "Cover Patio",
      "type": "tap",
      "service": "cover.close_cover"
    },
    {
      "entity": "cover.patio",
      "name": "Uncover Patio",
      "type": "tap",
      "service": "cover.open_cover"
    }
```

As I mentioned before, I appreciate the "on"/"off" text might not be what you want, but we can look into providing custom text fields in the JSON definition if the above works.

Please try this and get back to me so we can take the idea forwards.

**Comment by michaelwingender** [comment]
Ah. Ok. I did not understand from the examples that I can call the service cover.open_cover/cover.close_cover/cover.toggle. Yes, this works like a charm. So in general you already support it. I'm not even sure whether it need a change of the text fields. I can use the toggle, which you be fine for me personally.

**Comment by JosephAbbey** [comment]
We are looking into making the toggle more configurable, looking at https://www.home-assistant.io/integrations/switch.template/ for inspiration on the JSON format.
