### ISSUE TITLE
Battery reporting stops working when scrolling trough the widget

### ISSUE THREAD

**Issue by andychen27** [house-of-abbey/GarminHomeAssistant#43]
I have the application version installed on Fenix 7 Pro
I've set up the battery reporting and it worked fine, the issue occured if I add the homeassistant widget in my widget list and scroll through the homeassistant widget (where it shows "Homeassistant API: available Menu: available"), the background battery reporting will stop, I need to run the homeassitant application again to restart the reporting

**Comment by philipabbey** [comment]
So I think you mean when you scroll the carousel of glances rather than widgets, as your watch supports the former (widgets for older devices). Then yes, you have identified something I need to fix. Thank you.

**Comment by andychen27** [comment]
> h supp

yes, that's right, it's the glances
