### ISSUE TITLE
Confirm on type "tap" not working

### ISSUE THREAD

**Issue by jcastang** [house-of-abbey/GarminHomeAssistant#90]
Hello, 

Do not know if this is normal or not but adding a confirm on a tap action do not work (at least for me). 
```
   {
      "entity": "cover.portail",
      "name": "Ouvrir Portail",
      "type": "tap",
      "tap_action": {
        "service": "cover.open_cover"
        "confirm": true
      }
    },
```

Am I missing something ?
This lead to JSON not beeing read (Unavailable). 

"Toggle" cannot be an option as entity do not report state an is only usable via a service.

**Comment by philipabbey** [comment]
Yep! A comma.

Please perform a schema check on your JSON before raising an issue.

See https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/README.md#dashboard-definition for advice.
